# Generated by Django 5.2.17 on 2026-09-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('lecture_type', models.TextField(blank=True, default='')),
                ('teacher', models.TextField(blank=True, default='')),
                ('room', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('time_start', models.TextField()),
                ('time_end', models.TextField()),
                ('semester', models.TextField(blank=True, default='')),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'schedule_events',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'schedule_event_groups',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEventTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'schedule_event_teachers',
            },
        ),
        migrations.CreateModel(
            name='ScheduleGroup',
            fields=[
                ('slug', models.TextField(primary_key=True, serialize=False)),
                ('display_name', models.TextField(blank=True, default='')),
                ('group_name', models.TextField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'schedule_groups',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTeacher',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('external_id', models.TextField(blank=True, default='')),
                ('ad_account', models.TextField(blank=True, default='')),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'schedule_teachers',
            },
        ),
        migrations.DeleteModel(
            name='ScheduleLesson',
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['date'], name='idx_schedule_events_date'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['semester'], name='idx_schedule_events_sem'),
        ),
        migrations.AddConstraint(
            model_name='scheduleevent',
            constraint=models.UniqueConstraint(fields=('date', 'time_start', 'time_end', 'title', 'lecture_type', 'room'), name='idx_schedule_events_natural'),
        ),
        migrations.AddField(
            model_name='scheduleeventgroup',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleevent'),
        ),
        migrations.AddField(
            model_name='scheduleeventteacher',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleevent'),
        ),
        migrations.AddIndex(
            model_name='schedulegroup',
            index=models.Index(fields=['group_name'], name='idx_schedule_groups_name'),
        ),
        migrations.AddField(
            model_name='scheduleeventgroup',
            name='group',
            field=models.ForeignKey(db_column='group_slug', on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulegroup'),
        ),
        migrations.AddField(
            model_name='scheduleeventteacher',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleteacher'),
        ),
        migrations.AddConstraint(
            model_name='scheduleeventgroup',
            constraint=models.UniqueConstraint(fields=('event', 'group'), name='idx_schedule_event_groups_pair'),
        ),
        migrations.AddConstraint(
            model_name='scheduleeventteacher',
            constraint=models.UniqueConstraint(fields=('event', 'teacher'), name='idx_schedule_event_teachers_pair'),
        ),
    ]
