############################################################
#  [*] assistant 0001 — the four assistant tables
#
#  Enables the pgvector extension first (a no-op off
#  postgres — the sqlite test database skips it), creates
#  the knowledge base + conversation + telemetry tables,
#  and finishes with the HNSW cosine index over
#  support_chunks.embedding through a vendor-guarded
#  RunSQL: "USING hnsw" is postgres-only SQL that must
#  never reach sqlite, and pure SQL never drifts model
#  state, so `makemigrations --check` stays clean.
#
#  Head of its app's chain; the suite runs `makemigrations
#  --check`, so drift against models.py fails the tests.
############################################################
# Generated by Django 5.2.17 on 2026-09-15 15:21

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


############################################################
# PostgresRunSQL
############################################################
#
# migrations.RunSQL that runs only when the connection is
# postgres — the HNSW index below is pgvector SQL with no
# sqlite spelling at all.
############################################################

class PostgresRunSQL(migrations.RunSQL):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "postgresql":
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "postgresql":
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_last_active_at'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='AssistantThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('language', models.TextField(default='lt')),
                ('created_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_threads', to='users.user')),
            ],
            options={
                'db_table': 'assistant_threads',
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('pk', models.CompositePrimaryKey('thread_id', 'id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('format', models.TextField(default='aisdk-v7')),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('thread', models.ForeignKey(db_column='thread_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantthread')),
            ],
            options={
                'db_table': 'assistant_messages',
            },
        ),
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('client_version', models.TextField(blank=True, null=True)),
                ('language', models.TextField(default='lt')),
                ('model', models.TextField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('outcome', models.TextField(default='ok')),
                ('thread', models.ForeignKey(blank=True, db_column='thread_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='assistant.assistantthread')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_turns', to='users.user')),
            ],
            options={
                'db_table': 'assistant_turns',
            },
        ),
        migrations.CreateModel(
            name='SupportChunk',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('source_id', models.TextField()),
                ('title', models.TextField()),
                ('section', models.TextField(blank=True, null=True)),
                ('language', models.TextField(default='lt')),
                ('text', models.TextField()),
                ('content_hash', models.TextField()),
                ('embed_model', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('indexed_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'support_chunks',
                'indexes': [models.Index(fields=['source', 'source_id'], name='idx_support_chunks_source'), models.Index(fields=['last_seen_at'], name='idx_support_chunks_seen')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source__in', ('handbook', 'news'))), name='support_chunks_source_check'), models.CheckConstraint(condition=models.Q(('language__in', ('lt', 'en'))), name='support_chunks_language_check')],
            },
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['user', '-last_message_at'], name='idx_assistant_threads_user'),
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['deleted_at'], name='idx_assistant_threads_deleted'),
        ),
        migrations.AddConstraint(
            model_name='assistantthread',
            constraint=models.CheckConstraint(condition=models.Q(('language__in', ('lt', 'en'))), name='assistant_threads_language_check'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['thread', 'created_at'], name='idx_assistant_messages_thread'),
        ),
        migrations.AddIndex(
            model_name='assistantturn',
            index=models.Index(fields=['created_at'], name='idx_assistant_turns_created'),
        ),
        migrations.AddConstraint(
            model_name='assistantturn',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ('ok', 'error', 'aborted'))), name='assistant_turns_outcome_check'),
        ),
        PostgresRunSQL(
            sql="CREATE INDEX idx_support_chunks_embedding ON support_chunks "
                "USING hnsw (embedding vector_cosine_ops)",
            reverse_sql="DROP INDEX IF EXISTS idx_support_chunks_embedding",
        ),
    ]
