# Generated by Django 5.2.17 on 2026-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supportchunk',
            name='support_chunks_source_check',
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.CheckConstraint(condition=models.Q(('rating__in', (-1, 1)), ('rating__isnull', True), _connector='OR'), name='assistant_messages_rating_check'),
        ),
        migrations.AddConstraint(
            model_name='supportchunk',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ('handbook', 'news', 'curated'))), name='support_chunks_source_check'),
        ),
    ]
