# Generated by Django 5.2.17 on 2026-09-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_remove_supportchunk_support_chunks_source_check_and_more'),
        ('users', '0002_user_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantturn',
            name='prompt_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssistantPrompt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_prompts', to='users.user')),
            ],
            options={
                'db_table': 'assistant_prompts',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='assistant_prompts_one_active')],
            },
        ),
    ]
