# Generated by Django 5.2.17 on 2026-09-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_assistantturn_prompt_version_assistantprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantthread',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
